### ISSUE TITLE
Can't move to the end/beginning of a line (crash instead)

### ISSUE THREAD

**Issue by carlobaldassi** [Keno/REPL.jl#12]
With latest master, running `script/repl.jl` on linux:

1) Using `Ctrl-A` or `Ctrl-E` to move to the end/beginning of the line does this:

```
julia> "asdf"ERROR: type MIState has no field input_buffer
 in repl_keymap_func at /home/carlo/.julia/Readline/src/Readline.jl:797
 in prompt! at /home/carlo/.julia/Readline/src/Readline.jl:940
 in run_interface at /home/carlo/.julia/Readline/src/Readline.jl:922
 in run_repl at /home/carlo/.julia/REPL/src/REPL.jl:478
 in anonymous at no file:32
 in include_from_node1 at loading.jl:120
while loading /home/carlo/.julia/REPL/scripts/repl.jl, in expression starting on line 7
```

same error when trying other commands as `Ctrl-K` or `Ctrl-D` (this one on a non-empty line).

2) Using the Home/End keys inputs `H`/`F` characters in the line instead of moving the cursor

**Comment by ivarne** [comment]
I can confirm that this issue is on my linux machine also.

**Comment by Keno** [comment]
1. Is fixed by https://github.com/loladiro/Readline.jl/commit/61e3fee0978452d405e5173377bb7edbcbee835c
2. I've tried adding all the keybinding for home/end from [here](https://wiki.archlinux.org/index.php/Home_and_End_keys_not_working#Why_do_not_my_Home_and_End_keys_work_in_terminals.3F) in https://github.com/loladiro/Readline.jl/commit/ea1c06a54fe60937263ab282059205d3796a395a . Feel free to reopen if that problem persists.

**Comment by carlobaldassi** [comment]
works fine, thanks!
