### ISSUE TITLE
tab indenting vs. tab completion

### ISSUE THREAD

**Issue by StefanKarpinski** [Keno/REPL.jl#23]
The C REPL indents code by 2 spaces if you press tab when there are only whitespace characters before the cursor location on the current line; otherwise, it invokes tab completion. I've found this behavior to be quite handy, so this is a request to match that feature. Even though 4 spaces is the standard for Julia's base code, I chose 2 because it looked more natural in the REPL. I'm not sure what we'd want to choose for the new REPL – this would be a good time to change that if we wanted to go with 4.

**Comment by Keno** [comment]
Fixed in `Readline.jl`

**Comment by StefanKarpinski** [comment]
I'm curious how this is a readline issue. It seems like it should be a REPL configuration thing, no?

**Comment by Keno** [comment]
`REPL.jl` provides the completion logic. `Readline.jl` provides basic keybindings, including the hooks for tab completions. The reason for this separation is that tab completion is hardly Julia REPL specific and is useful in other contexts as well.

**Comment by Keno** [comment]
Though I suppose you're right. I could make this a property of the completion hook. Might be better that way, but I'm not sure since wanting to not complete after whitespace is very common and overriding the key binding is extremely easy. I think for now I'm gonna leave it like this and if a case comes up where a different behavior is needed, I'll reconsider.

**Comment by StefanKarpinski** [comment]
Ok, that seems sane. For what it's worth, this is already infinitely easier to program than GNU readline.
